// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_DirectoryDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileSystem;

public interface _DirectoryDel extends Ice._ObjectDel
{
    String[] listContent(String dirPath, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               DirectoryNotExistsException;
}
