// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DirectoryV2Prx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileSystem;

public interface DirectoryV2Prx extends Ice.ObjectPrx
{
    public String[] listFiles(String dirPath)
        throws DirectoryNotExistsException;

    public String[] listFiles(String dirPath, java.util.Map<String, String> __ctx)
        throws DirectoryNotExistsException;

    public Ice.AsyncResult begin_listFiles(String dirPath);

    public Ice.AsyncResult begin_listFiles(String dirPath, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_listFiles(String dirPath, Ice.Callback __cb);

    public Ice.AsyncResult begin_listFiles(String dirPath, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_listFiles(String dirPath, Callback_DirectoryV2_listFiles __cb);

    public Ice.AsyncResult begin_listFiles(String dirPath, java.util.Map<String, String> __ctx, Callback_DirectoryV2_listFiles __cb);

    public String[] end_listFiles(Ice.AsyncResult __result)
        throws DirectoryNotExistsException;
}
