// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DirectoryV2Holder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileSystem;

public final class DirectoryV2Holder extends Ice.ObjectHolderBase<DirectoryV2>
{
    public
    DirectoryV2Holder()
    {
    }

    public
    DirectoryV2Holder(DirectoryV2 value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        try
        {
            value = (DirectoryV2)v;
        }
        catch(ClassCastException ex)
        {
            IceInternal.Ex.throwUOE(type(), v.ice_id());
        }
    }

    public String
    type()
    {
        return _DirectoryV2Disp.ice_staticId();
    }
}
