// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DirectoryV2PrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileSystem;

public final class DirectoryV2PrxHolder
{
    public
    DirectoryV2PrxHolder()
    {
    }

    public
    DirectoryV2PrxHolder(DirectoryV2Prx value)
    {
        this.value = value;
    }

    public DirectoryV2Prx value;
}
