
package agh.sr.ws.simplest.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://www.example.org/Calculator/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param b
     * @param c
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddOperation", action = "http://www.example.org/Calculator/AddOperation")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "AddOperation", targetNamespace = "http://www.example.org/Calculator/", className = "agh.sr.ws.simplest.jaxws.AddOperation")
    @ResponseWrapper(localName = "AddOperationResponse", targetNamespace = "http://www.example.org/Calculator/", className = "agh.sr.ws.simplest.jaxws.AddOperationResponse")
    public int addOperation(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b,
        @WebParam(name = "c", targetNamespace = "")
        int c);

    /**
     * 
     * @param dividend
     * @param divisor
     * @return
     *     returns double
     */
    @WebMethod(operationName = "DivideOperation", action = "http://www.example.org/Calculator/DivideOperation")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "DivideOperation", targetNamespace = "http://www.example.org/Calculator/", className = "agh.sr.ws.simplest.jaxws.DivideOperation")
    @ResponseWrapper(localName = "DivideOperationResponse", targetNamespace = "http://www.example.org/Calculator/", className = "agh.sr.ws.simplest.jaxws.DivideOperationResponse")
    public double divideOperation(
        @WebParam(name = "dividend", targetNamespace = "")
        int dividend,
        @WebParam(name = "divisor", targetNamespace = "")
        int divisor);

}
