// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_DirectoryV2Operations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice;

public interface _DirectoryV2Operations
{
    String[] listFiles(String dirPath, Ice.Current __current)
        throws DirectoryNotExistsException;
}
