// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DirectoryPrxHelper.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice;

public final class DirectoryPrxHelper extends Ice.ObjectPrxHelperBase implements DirectoryPrx
{
    public String[]
    listContent(String dirPath)
        throws DirectoryNotExistsException
    {
        return listContent(dirPath, null, false);
    }

    public String[]
    listContent(String dirPath, java.util.Map<String, String> __ctx)
        throws DirectoryNotExistsException
    {
        return listContent(dirPath, __ctx, true);
    }

    private String[]
    listContent(String dirPath, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws DirectoryNotExistsException
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("listContent");
                __delBase = __getDelegate(false);
                _DirectoryDel __del = (_DirectoryDel)__delBase;
                return __del.listContent(dirPath, __ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __cnt = __handleExceptionWrapperRelaxed(__delBase, __ex, null, __cnt);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __listContent_name = "listContent";

    public Ice.AsyncResult begin_listContent(String dirPath)
    {
        return begin_listContent(dirPath, null, false, null);
    }

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx)
    {
        return begin_listContent(dirPath, __ctx, true, null);
    }

    public Ice.AsyncResult begin_listContent(String dirPath, Ice.Callback __cb)
    {
        return begin_listContent(dirPath, null, false, __cb);
    }

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_listContent(dirPath, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_listContent(String dirPath, Callback_Directory_listContent __cb)
    {
        return begin_listContent(dirPath, null, false, __cb);
    }

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx, Callback_Directory_listContent __cb)
    {
        return begin_listContent(dirPath, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__listContent_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __listContent_name, __cb);
        try
        {
            __result.__prepare(__listContent_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(dirPath);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public String[] end_listContent(Ice.AsyncResult __result)
        throws DirectoryNotExistsException
    {
        Ice.AsyncResult.__check(__result, this, __listContent_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(DirectoryNotExistsException __ex)
            {
                throw __ex;
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
            }
        }
        String[] __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = Ice.StringSeqHelper.read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public static DirectoryPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DirectoryPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DirectoryPrxHelper __h = new DirectoryPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DirectoryPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DirectoryPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DirectoryPrxHelper __h = new DirectoryPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DirectoryPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DirectoryPrxHelper __h = new DirectoryPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DirectoryPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DirectoryPrxHelper __h = new DirectoryPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DirectoryPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DirectoryPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                DirectoryPrxHelper __h = new DirectoryPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DirectoryPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DirectoryPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DirectoryPrxHelper __h = new DirectoryPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::FileSystem::Directory",
        "::Ice::Object"
    };

    public static String
    ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _DirectoryDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _DirectoryDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, DirectoryPrx v)
    {
        __os.writeProxy(v);
    }

    public static DirectoryPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DirectoryPrxHelper result = new DirectoryPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
