// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DirectoryPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice;

public interface DirectoryPrx extends Ice.ObjectPrx
{
    public String[] listContent(String dirPath)
        throws DirectoryNotExistsException;

    public String[] listContent(String dirPath, java.util.Map<String, String> __ctx)
        throws DirectoryNotExistsException;

    public Ice.AsyncResult begin_listContent(String dirPath);

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_listContent(String dirPath, Ice.Callback __cb);

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_listContent(String dirPath, Callback_Directory_listContent __cb);

    public Ice.AsyncResult begin_listContent(String dirPath, java.util.Map<String, String> __ctx, Callback_Directory_listContent __cb);

    public String[] end_listContent(Ice.AsyncResult __result)
        throws DirectoryNotExistsException;
}
