
package com.hascode.tutorial.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BookServicePortType", targetNamespace = "http://www.hascode.com/bookService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServicePortType {


    /**
     * 
     * @param bookServiceRequest
     * @return
     *     returns com.hascode.tutorial.ws.service.BookServiceResponseType
     */
    @WebMethod(action = "http://www.hascode.com/bookService/fetchBooks")
    @WebResult(name = "BookServiceResponse", targetNamespace = "http://www.hascode.com/bookService/1.0", partName = "BookServiceResponse")
    public BookServiceResponseType fetchBooks(
        @WebParam(name = "BookServiceRequest", targetNamespace = "http://www.hascode.com/bookService/1.0", partName = "BookServiceRequest")
        BookServiceRequestType bookServiceRequest);

}
